### ISSUE TITLE
Add compile script and code coverage display

### ISSUE THREAD

**Issue by QuentinCG** [xtofpic/GS1#1]
Hello xtofpic ! 

I would suggest adding a script to automatically build this library + launch your test + have a code coverage (using your test).
There are [travis ](https://travis-ci.org/) and [codecov.io](https://codecov.io) which are free for open source projects.
Only requirement: create an account on those websites and add a `.travis.yml` file on project root folder. A build will then be launched at every commit (or with a manual trigger directly on the travis website)!
The build result and % of code coverage can then be directly displayed on the readme of your project if you want to (travis 'badge' and codecov 'badge') !

A potential example of the .travis.yml file (not tested) :
```
language: cpp
matrix:
  include:
  - name: Linux
    os: linux
    dist: xenial
    before_install:
    - sudo apt update -qq
    - sudo apt install build-essential
    # Dependency for test coverage
    - sudo apt install python3-pip
    - sudo pip3 install codecov
    # Dependency for Datamatrix library
    - sudo pip3 install conan
    compiler:
    - g++
    script:
    - cmake -G "Eclipse CDT4 - Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_ECLIPSE_GENERATE_SOURCE_PROJECT=TRUE -DCMAKE_ECLIPSE_MAKE_ARGUMENTS=-j12 -DCMAKE_ECLIPSE_VERSION=4.17 ..
    - make
    - env CTEST_OUTPUT_ON_FAILURE=1 make test
    - coverage run -p ./test
    # Prepare results before sending them back  codecov
    - coverage combineto
    after_success:
    # Push code coverage result into codecov.io
    - bash <(curl -s https://codecov.io/bash)
```

You can also add a `codecov.yml` file if you want to add specific requirements for the code coverage:
```
codecov:
  require_ci_to_pass: yes

coverage:
  ignore:
    - "CMake/**"
    - "tests/**"
```

Example of a project with build and code coverage (lib tested with multiple OS if you want to be sure your library is usable everywhere) :
https://github.com/QuentinCG/QDhcpDiscovery/blob/master/.travis.yml
